# Production Docker Compose Override
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  db:
    restart: always
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    # Don't expose DB port to host in production
    ports: []
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  web:
    restart: always
    command: gunicorn user_service.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
      - ALLOWED_HOSTS=yourdomain.com,api.yourdomain.com
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
    secrets:
      - db_password
      - django_secret_key
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

secrets:
  db_password:
    file: ./secrets/db_password.txt
  django_secret_key:
    file: ./secrets/django_secret_key.txt