# Generated by Django 5.1.2 on 2025-11-01 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Unique verification token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
                ('user', models.ForeignKey(help_text='User associated with this verification token', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='email_verif_user_id_bef55e_idx'), models.Index(fields=['token'], name='email_verif_token_df7c5e_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_770728_idx')],
            },
        ),
    ]
